on: workflow_dispatch
name: Deploy Azure Resource Manager (ARM) Template
jobs:
  build-and-deploy:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
      - uses: Azure/arm-deploy@v2
        with:
          resourceGroupName: github-action-arm-rg
          template: ./../InfrastructureAsCode/main.bicep
          additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"
